#!/bin/zsh
set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ==================================================================
# PROCESSES
# ==================================================================

killall node || true

# ==================================================================
# ARTIFACTS
# ==================================================================

# Remove unused Homebrew artifacts
brew cleanup
brew services cleanup

homebrew_casks=($(brew cask list))
for cask in "${homebrew_casks[@]}"; do
  brew cu "$cask" --all --yes --cleanup
done

# Remove .DS_Store files
find ~ -name '.DS_Store' -delete

# Disable the default behavior of `zsh` if no files match
setopt NULL_GLOB;

# Clear the Downloads directory
rm -rf ~/Downloads/*

# Empty the trash
rm -rf ~/.Trash/*

# Re-enable default behavior
unset NULL_GLOB;

# ==================================================================
# REPO BRANCHES
# ==================================================================

deep-git-prune ()
{
  IFS=$'\n\t'

  # Remove merged git branches and stale remote references other
  # than master and the current branch in each git directory
  set +e
  LOCAL_BRANCHES=$(git branch --merged master | grep -v -e 'master' -e '\*' | tr -d ' ')
  set -e

  if [[ -n "$LOCAL_BRANCHES" ]]; then
    for BRANCH in $LOCAL_BRANCHES; do
      git branch -d "$BRANCH"
    done
  fi

  git remote prune origin
}

cd "$HOME/Sites"
for i in */.git; do ( echo $i; cd $i/..; deep-git-prune; ); done

cd "$HOME/Sites/cnvs"
for i in */.git; do ( echo $i; cd $i/..; deep-git-prune; ); done

cd "$HOME/Sites/ozaukeechristian"
for i in */.git; do ( echo $i; cd $i/..; deep-git-prune; ); done
