#!/usr/bin/env bash
set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup
# has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ==================================================================
# PACKAGES
# ==================================================================

# HOMEBREW
echo "Updating Homebrew packages"
brew update
brew upgrade

homebrew_casks=($(brew cask list))
for cask in "${homebrew_casks[@]}"; do
  if [ "$cask" = "1password" ] || [ "$cask" = "bettertouchtool" ] ; then
    continue;
  fi
  brew cu -f -a "$cask"
done

# COMPOSER
echo "Updating Composer"
composer self-update

echo "Updating Composer packages"
composer global update

# TLDR
echo "Updating TLDR"
tldr --update

# ==================================================================
# MAC APP STORE
# ==================================================================

echo "Upgrading Mac App Store apps"
mas upgrade

# ==================================================================
# MACOS
# ==================================================================

echo "Upgrading macOS"
sudo softwareupdate -ia
