#!/usr/bin/env bash
set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup
# has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


# ==================================================================
# PACKAGES
# ==================================================================

# HOMEBREW
echo "Updating Homebrew packages"
brew update
brew upgrade

# NPM
echo "Updating npm"
npm install npm@latest -g

# COMPOSER
echo "Updating Composer"
sudo composer self-update

echo "Updating Composer packages"
composer global update


# ==================================================================
# MAC APP STORE
# ==================================================================

echo "Upgrading Mac App Store apps"
mas upgrade


# ==================================================================
# MACOS
# ==================================================================

echo "Upgrading macOS"
sudo softwareupdate -ia